# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.srcs/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/kria_eth_top_axi_ethernet_0_2.xci
# IP: The module: 'kria_eth_top_axi_ethernet_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/bd_17e7.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_17e7 || ORIG_REF_NAME==bd_17e7} -quiet] -quiet

# IP: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_0/bd_17e7_eth_buf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_17e7_eth_buf_0 || ORIG_REF_NAME==bd_17e7_eth_buf_0} -quiet] -quiet

# IP: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_1/bd_17e7_mac_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_17e7_mac_0 || ORIG_REF_NAME==bd_17e7_mac_0} -quiet] -quiet

# IP: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_2/bd_17e7_c_shift_ram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_17e7_c_shift_ram_0_0 || ORIG_REF_NAME==bd_17e7_c_shift_ram_0_0} -quiet] -quiet

# IP: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_3/bd_17e7_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_17e7_c_counter_binary_0_0 || ORIG_REF_NAME==bd_17e7_c_counter_binary_0_0} -quiet] -quiet

# IP: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_4/bd_17e7_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_17e7_xlconstant_0_0 || ORIG_REF_NAME==bd_17e7_xlconstant_0_0} -quiet] -quiet

# IP: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_5/bd_17e7_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_17e7_util_vector_logic_0_0 || ORIG_REF_NAME==bd_17e7_util_vector_logic_0_0} -quiet] -quiet

# XDC: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/bd_17e7_ooc.xdc

# XDC: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/kria_eth_top_axi_ethernet_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_eth_top_axi_ethernet_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/synth/kria_eth_top_axi_ethernet_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_eth_top_axi_ethernet_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/synth/kria_eth_top_axi_ethernet_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_eth_top_axi_ethernet_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.srcs/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/kria_eth_top_axi_ethernet_0_2.xci
# IP: The module: 'kria_eth_top_axi_ethernet_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/bd_17e7.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_17e7 || ORIG_REF_NAME==bd_17e7} -quiet] -quiet

# IP: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_0/bd_17e7_eth_buf_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_17e7_eth_buf_0 || ORIG_REF_NAME==bd_17e7_eth_buf_0} -quiet] -quiet

# IP: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_1/bd_17e7_mac_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_17e7_mac_0 || ORIG_REF_NAME==bd_17e7_mac_0} -quiet] -quiet

# IP: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_2/bd_17e7_c_shift_ram_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_17e7_c_shift_ram_0_0 || ORIG_REF_NAME==bd_17e7_c_shift_ram_0_0} -quiet] -quiet

# IP: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_3/bd_17e7_c_counter_binary_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_17e7_c_counter_binary_0_0 || ORIG_REF_NAME==bd_17e7_c_counter_binary_0_0} -quiet] -quiet

# IP: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_4/bd_17e7_xlconstant_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_17e7_xlconstant_0_0 || ORIG_REF_NAME==bd_17e7_xlconstant_0_0} -quiet] -quiet

# IP: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_5/bd_17e7_util_vector_logic_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_17e7_util_vector_logic_0_0 || ORIG_REF_NAME==bd_17e7_util_vector_logic_0_0} -quiet] -quiet

# XDC: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/bd_17e7_ooc.xdc

# XDC: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/kria_eth_top_axi_ethernet_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_eth_top_axi_ethernet_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/synth/kria_eth_top_axi_ethernet_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_eth_top_axi_ethernet_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/synth/kria_eth_top_axi_ethernet_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_eth_top_axi_ethernet_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
