# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/default.xdc

# Block Designs: bd/kr260_starter_kit/kr260_starter_kit.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_starter_kit || ORIG_REF_NAME==kr260_starter_kit} -quiet] -quiet

# IP: bd/kr260_starter_kit/ip/kr260_starter_kit_xlslice_0_0/kr260_starter_kit_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_starter_kit_xlslice_0_0 || ORIG_REF_NAME==kr260_starter_kit_xlslice_0_0} -quiet] -quiet

# IP: bd/kr260_starter_kit/ip/kr260_starter_kit_zynq_ultra_ps_e_0_0/kr260_starter_kit_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kr260_starter_kit_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==kr260_starter_kit_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: /tmp/tmp.rcD1Rez4M9/temp/hw_design/k26_starter_kits/kr260/project/kr260_starter_kit.gen/sources_1/bd/kr260_starter_kit/kr260_starter_kit_ooc.xdc
