#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2022.2.2 (64-bit)
#
# Filename    : kria_eth_top.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Apr 04 18:47:50 MDT 2023
# SW Build 3788238 on Tue Feb 21 19:59:23 MST 2023
#
# Tool Version Limit: 2022.10 
#
# usage: kria_eth_top.sh [-help]
# usage: kria_eth_top.sh [-lib_map_path]
# usage: kria_eth_top.sh [-noclean_files]
# usage: kria_eth_top.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'kria_eth_top.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64 "

# Set vhdlan compile options
vhdlan_opts="-full64 "

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log "

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_13 zynq_ultra_ps_e_vip_v1_0_13 xil_defaultlib axi_lite_ipif_v3_0_4 axi_ethernet_buffer_v2_0_24 xbip_utils_v3_0_10 xbip_pipe_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_18 tri_mode_ethernet_mac_v9_0_25 c_reg_fd_v12_0_6 c_mux_bit_v12_0_6 c_shift_ram_v12_0_14 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_6 xbip_addsub_v3_0_6 c_addsub_v12_0_14 c_gate_bit_v12_0_6 xbip_counter_v3_0_6 c_counter_binary_v12_0_15 xlconstant_v1_1_7 util_vector_logic_v2_0_2 lib_pkg_v1_0_2 fifo_generator_v13_2_7 lib_fifo_v1_0_16 lib_srl_fifo_v1_0_2 lib_cdc_v1_0_2 axi_datamover_v5_1_29 axi_sg_v4_1_15 axi_dma_v7_1_28 proc_sys_reset_v5_0_13 smartconnect_v1_0 axi_register_slice_v2_1_27 generic_baseblocks_v2_1_0 axi_data_fifo_v2_1_26 axi_crossbar_v2_1_28 axi_intc_v4_1_17 xlconcat_v2_1_4 axi_clock_converter_v2_1_26 axi_protocol_converter_v2_1_27)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "kria_eth_top.sh - Script generated by export_simulation (Vivado v2022.2.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/tools/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ffc2/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_zynq_ultra_ps_e_0_0/sim/kria_eth_top_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_clk_wiz_2/kria_eth_top_clk_wiz_2_clk_wiz.v" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_clk_wiz_2/kria_eth_top_clk_wiz_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_ethernet_buffer_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/1ed2/hdl/axi_ethernet_buffer_v2_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_0/sim/bd_17e7_eth_buf_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/364f/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_18 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ab19/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work tri_mode_ethernet_mac_v9_0_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ba0c/hdl/tri_mode_ethernet_mac_v9_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work tri_mode_ethernet_mac_v9_0_25 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ba0c/hdl/tri_mode_ethernet_mac_v9_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_1/synth/common/bd_17e7_mac_0_block_reset_sync.v" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_1/synth/common/bd_17e7_mac_0_block_sync_block.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_1/synth/bd_17e7_mac_0_axi4_lite_ipif_top.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_1/synth/bd_17e7_mac_0_axi4_lite_ipif_wrapper.v" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_1/synth/bd_17e7_mac_0_clk_en_gen.v" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_1/synth/physical/bd_17e7_mac_0_rgmii_v2_0_if.v" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_1/synth/statistics/bd_17e7_mac_0_vector_decode.v" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_1/synth/bd_17e7_mac_0_block.v" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_1/synth/bd_17e7_mac_0_support.v" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_1/synth/bd_17e7_mac_0_support_resets.v" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_1/synth/bd_17e7_mac_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work c_reg_fd_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/edec/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_mux_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ecb4/hdl/c_mux_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_shift_ram_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/2598/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_2/sim/bd_17e7_c_shift_ram_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/cfdd/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ebb8/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_gate_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7161/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_counter_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/9ac8/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_counter_binary_v12_0_15 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/e1e1/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_3/sim/bd_17e7_c_counter_binary_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/badb/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_4/sim/bd_17e7_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/3d84/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/ip/ip_5/sim/bd_17e7_util_vector_logic_0_0.v" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/bd_0/sim/bd_17e7.v" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/sim/kria_eth_top_axi_ethernet_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/83df/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_7 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/83df/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/83df/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_16 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/6c82/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_29 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/2237/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_15 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/751a/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_28 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/70c4/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_dma_0/sim/kria_eth_top_axi_ethernet_0_dma_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/sim/bd_2701.v" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_0/sim/bd_2701_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_1/sim/bd_2701_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_2/sim/bd_2701_arsw_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_3/sim/bd_2701_rsw_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_4/sim/bd_2701_awsw_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_5/sim/bd_2701_wsw_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_6/sim/bd_2701_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/be1f/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_7/sim/bd_2701_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_8/sim/bd_2701_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/637d/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_9/sim/bd_2701_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f38e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_10/sim/bd_2701_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_11/sim/bd_2701_sarn_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_12/sim/bd_2701_srn_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_13/sim/bd_2701_s01mmu_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_14/sim/bd_2701_s01tr_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_15/sim/bd_2701_s01sic_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_16/sim/bd_2701_s01a2s_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_17/sim/bd_2701_sawn_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_18/sim/bd_2701_swn_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_19/sim/bd_2701_sbn_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_20/sim/bd_2701_s02mmu_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_21/sim/bd_2701_s02tr_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_22/sim/bd_2701_s02sic_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_23/sim/bd_2701_s02a2s_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_24/sim/bd_2701_sarn_1.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_25/sim/bd_2701_srn_1.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_26/sim/bd_2701_sawn_1.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_27/sim/bd_2701_swn_1.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_28/sim/bd_2701_sbn_1.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/9cc5/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_29/sim/bd_2701_m00s2a_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_30/sim/bd_2701_m00arn_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_31/sim/bd_2701_m00rn_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_32/sim/bd_2701_m00awn_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_33/sim/bd_2701_m00wn_0.sv" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_34/sim/bd_2701_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/6bba/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/bd_0/ip/ip_35/sim/bd_2701_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/sim/kria_eth_top_axi_smc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/3111/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_28 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/c40e/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_xbar_1/sim/kria_eth_top_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_rst_ps8_0_99M_0/sim/kria_eth_top_rst_ps8_0_99M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_17 $vhdlan_opts \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/802b/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_axi_intc_0_2/sim/kria_eth_top_axi_intc_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_xlconcat_0_0/sim/kria_eth_top_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_proc_sys_reset_0_0/sim/kria_eth_top_proc_sys_reset_0_0.vhd" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_proc_sys_reset_1_0/sim/kria_eth_top_proc_sys_reset_1_0.vhd" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_proc_sys_reset_125_0/sim/kria_eth_top_proc_sys_reset_125_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/kria_eth_top/sim/kria_eth_top.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/b8be/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_auto_cc_3/sim/kria_eth_top_auto_cc_3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/aeb3/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/7698" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../kria_state_machine.gen/sources_1/bd/kria_eth_top/ipshared/66be/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_auto_pc_0/sim/kria_eth_top_auto_pc_0.v" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_auto_cc_0/sim/kria_eth_top_auto_cc_0.v" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_auto_cc_1/sim/kria_eth_top_auto_cc_1.v" \
    "$ref_dir/../../../bd/kria_eth_top/ip/kria_eth_top_auto_cc_2/sim/kria_eth_top_auto_cc_2.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.kria_eth_top xil_defaultlib.glbl -o kria_eth_top_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./kria_eth_top_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./kria_eth_top.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key kria_eth_top_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc kria_eth_top_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./kria_eth_top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: kria_eth_top.sh [-help]\n\
Usage: kria_eth_top.sh [-lib_map_path]\n\
Usage: kria_eth_top.sh [-reset_run]\n\
Usage: kria_eth_top.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
