# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.srcs/sources_1/bd/kria_eth_top/ip/kria_eth_top_xbar_1/kria_eth_top_xbar_1.xci
# IP: The module: 'kria_eth_top_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_xbar_1/kria_eth_top_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_eth_top_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.srcs/sources_1/bd/kria_eth_top/ip/kria_eth_top_xbar_1/kria_eth_top_xbar_1.xci
# IP: The module: 'kria_eth_top_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/ip/kria_eth_top_xbar_1/kria_eth_top_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_eth_top_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
