# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/kria_eth_top/kria_eth_top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_eth_top || ORIG_REF_NAME==kria_eth_top} -quiet] -quiet

# IP: bd/kria_eth_top/ip/kria_eth_top_zynq_ultra_ps_e_0_0/kria_eth_top_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_eth_top_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==kria_eth_top_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/kria_eth_top/ip/kria_eth_top_clk_wiz_2/kria_eth_top_clk_wiz_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_eth_top_clk_wiz_2 || ORIG_REF_NAME==kria_eth_top_clk_wiz_2} -quiet] -quiet

# IP: bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_2/kria_eth_top_axi_ethernet_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_eth_top_axi_ethernet_0_2 || ORIG_REF_NAME==kria_eth_top_axi_ethernet_0_2} -quiet] -quiet

# IP: bd/kria_eth_top/ip/kria_eth_top_axi_ethernet_0_dma_0/kria_eth_top_axi_ethernet_0_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_eth_top_axi_ethernet_0_dma_0 || ORIG_REF_NAME==kria_eth_top_axi_ethernet_0_dma_0} -quiet] -quiet

# IP: bd/kria_eth_top/ip/kria_eth_top_axi_smc_0/kria_eth_top_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_eth_top_axi_smc_0 || ORIG_REF_NAME==kria_eth_top_axi_smc_0} -quiet] -quiet

# IP: bd/kria_eth_top/ip/kria_eth_top_xbar_1/kria_eth_top_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_eth_top_xbar_1 || ORIG_REF_NAME==kria_eth_top_xbar_1} -quiet] -quiet

# IP: bd/kria_eth_top/ip/kria_eth_top_ps8_0_axi_periph_1/kria_eth_top_ps8_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_eth_top_ps8_0_axi_periph_1 || ORIG_REF_NAME==kria_eth_top_ps8_0_axi_periph_1} -quiet] -quiet

# IP: bd/kria_eth_top/ip/kria_eth_top_rst_ps8_0_99M_0/kria_eth_top_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_eth_top_rst_ps8_0_99M_0 || ORIG_REF_NAME==kria_eth_top_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/kria_eth_top/ip/kria_eth_top_xlconcat_0_0/kria_eth_top_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_eth_top_xlconcat_0_0 || ORIG_REF_NAME==kria_eth_top_xlconcat_0_0} -quiet] -quiet

# IP: bd/kria_eth_top/ip/kria_eth_top_proc_sys_reset_0_0/kria_eth_top_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_eth_top_proc_sys_reset_0_0 || ORIG_REF_NAME==kria_eth_top_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/kria_eth_top/ip/kria_eth_top_proc_sys_reset_1_0/kria_eth_top_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_eth_top_proc_sys_reset_1_0 || ORIG_REF_NAME==kria_eth_top_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/kria_eth_top/ip/kria_eth_top_proc_sys_reset_125_0/kria_eth_top_proc_sys_reset_125_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_eth_top_proc_sys_reset_125_0 || ORIG_REF_NAME==kria_eth_top_proc_sys_reset_125_0} -quiet] -quiet

# IP: bd/kria_eth_top/ip/kria_eth_top_auto_cc_2/kria_eth_top_auto_cc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_eth_top_auto_cc_2 || ORIG_REF_NAME==kria_eth_top_auto_cc_2} -quiet] -quiet

# IP: bd/kria_eth_top/ip/kria_eth_top_auto_pc_0/kria_eth_top_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_eth_top_auto_pc_0 || ORIG_REF_NAME==kria_eth_top_auto_pc_0} -quiet] -quiet

# IP: bd/kria_eth_top/ip/kria_eth_top_auto_cc_0/kria_eth_top_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_eth_top_auto_cc_0 || ORIG_REF_NAME==kria_eth_top_auto_cc_0} -quiet] -quiet

# IP: bd/kria_eth_top/ip/kria_eth_top_auto_cc_1/kria_eth_top_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_eth_top_auto_cc_1 || ORIG_REF_NAME==kria_eth_top_auto_cc_1} -quiet] -quiet

# XDC: /home/denmann99/Documents/kria_eth/hw/kria_state_machine/kria_state_machine.gen/sources_1/bd/kria_eth_top/kria_eth_top_ooc.xdc
